name: IO22
version: ${project.version}
main: me.pondhalf.plugin.IO22
api-version: 1.16
authors: [ PONDHALF ]
commands:
  tpa:
    usage: /<command>
    description: Send request teleport.
  tpaccept:
    usage: /<command>
    description: Accept teleport request.
  io22:
    usage: /<command>
    description: Main command
    permission: io22.command.reload
  dev:
    usage: /<command>
    description: Developer command
    permission: io22.command.dev
  home:
    usage: /<command>
    description: teleport to home command
  sethome:
    usage: /<command>
    description: Set home command
  back:
    usage: /<command>
    description: Return player to death waypoint
  creative:
    usage: /<command>
    description: Go to creative world